### ISSUE TITLE
Separating SVG from collaboration

### ISSUE THREAD

**Issue by sdhutchins** [r-bioinformatics/collaboration#13]
Are there plans to separate the `SVG` package/module from this repo and just turn this one into a place for only ideas, @apfejes?

**Comment by apfejes** [comment]
This is already a separate repo from the edgePy repo- and I'm not sure what you mean "for only ideas".  Can you explain that?

**Comment by sdhutchins** [comment]
In terms of the [idea page](https://github.com/r-bioinformatics/collaboration/blob/master/idea-page.md) and repo name, that stuff isn't really related to SVG directly.

**Comment by apfejes** [comment]
Oh, I see what you mean.

The idea page was somewhat of a temporary resting place for ideas.  I think that'll eventually just be killed off when we figure out the parameters of what were going to to.  Consider it a boot strapping tool, rather than a permanent part of this project.

The SVG library should eventually become an actually SVG project - at which point we'll probably want to rename this particular repo. 

All these things are subject to change, depending on people's interests and what moves forward in what order.

**Comment by sdhutchins** [comment]
Sounds perfect to me! While everyone is `edgePy`ing, I want to play around with this (hopefully this weekend).

**Comment by apfejes** [comment]
please do - I'm actively using the main branch of this project in my work place, so please make commits to a branch. (-:
